name: vmsrouting
author: ComitFS Ltd
email: support@comitfs.com
url: http://www.comitfs.com
version: '0.1'
title: 'Routing'
icon: rocket
# dependency on Core is required for UI plugins
dependencies:
    - !PluginDependency { plugin_name: core }
    - !OptionalPluginDependency { plugin_name: sip }
   
resources:
    - 'resources/js/module.es'
    - 'resources/js/routing.es'
    - 'resources/js/controllers/index.controller.es'
    - 'resources/partial/index.html'
    - 'ng:vms.vmsrouting'
    # - 'ng:my.plugin.angular-submodule'
    # - 'resources/module.js'
    # - 'resources/module.coffee'
    # - 'resources/styles.css'
    # - 'resources/styles.less'
