name: inroutes
author: ComitFS
email: support@comitfs.com
url: http://www.comitfs.com
version: '0.1'
title: 'routing'
icon: rocket
# dependency on Core is required for UI plugins
dependencies:
    - !PluginDependency {
        plugin_name: core
    }
    - !OptionalPluginDependency {
       plugin_name: vmsrouting
    }
  
resources:
    - 'resources/js/module.es'
    - 'resources/js/routing.es'
    - 'resources/js/controllers/index.controller.es'
    - 'resources/partial/index.html'
    - 'ng:vms.inroutes'
   