name: configure
author: Globility Ltd
email: support@globility.co.uk
url: http://www.globility.co.uk
version: '0.1'
title: 'conference'
icon: wrench
# dependency on Core is required for UI plugins
dependencies:
    - !PluginDependency {
        plugin_name: core
    }
    - !OptionalPluginDependency {
       plugin_name: conference
    }
    # - !ModuleDependency {
    #   module_name: requests
    # }
    # - !BinaryDependency {
    #   binary_name: curl
    # }
resources:
    - 'resources/js/module.es'
    - 'resources/js/routing.es'
    - 'resources/js/controllers/index.controller.es'
    - 'resources/partial/index.html'
    - 'ng:vms.configure'
    # - 'ng:my.plugin.angular-submodule'
    # - 'resources/module.js'
    # - 'resources/module.coffee'
    # - 'resources/styles.css'
    # - 'resources/styles.less'
